# docker-compose run -it --rm development
version: "3"
services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh
    volumes:
      - .:/workspace:cached
    ports:
      - 9000:9000
