# docker-compose run -it --rm builder
version: "3"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh
    volumes:
      - type: bind
        source: .
        target: /rom